name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Conan
      run: python -m pip install conan

    - name: Conan remote update
      run: conan remote update conancenter --url="https://center2.conan.io" || true

    - name: Conan detect profile
      run: conan profile detect
    - name: Conan update profile
      run: conan config set "profiles.default.settings.compiler.cppstd=20"
    - name: Conan install
      run: conan install . --output-folder=build --build=missing
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake
    - name: Build
      run: cmake --build build --config Release -- -j
    - name: Run tests
      run: ctest --test-dir build --output-on-failure
    - name: Generate docs
      run: cmake --build build --target doc
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test_results.xml
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: build/docs